/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAddWorkoutRouteImport } from './routes/_authenticated/add-workout'
import { Route as AuthenticatedWorkoutsRouteImport } from './routes/_authenticated/workouts'
import { Route as AuthenticatedWorkoutsIdRouteImport } from './routes/_authenticated/workouts.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAddWorkoutRoute = AuthenticatedAddWorkoutRouteImport.update({
  id: '/add-workout',
  path: '/add-workout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkoutsRoute = AuthenticatedWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkoutsIdRoute = AuthenticatedWorkoutsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedWorkoutsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/add-workout': typeof AuthenticatedAddWorkoutRoute
  '/workouts': typeof AuthenticatedWorkoutsRouteWithChildren
  '/workouts/$id': typeof AuthenticatedWorkoutsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/add-workout': typeof AuthenticatedAddWorkoutRoute
  '/workouts': typeof AuthenticatedWorkoutsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/workouts/$id': typeof AuthenticatedWorkoutsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/add-workout': typeof AuthenticatedAddWorkoutRoute
  '/_authenticated/workouts': typeof AuthenticatedWorkoutsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/workouts/$id': typeof AuthenticatedWorkoutsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/add-workout'
    | '/workouts'
    | '/workouts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/add-workout'
    | '/workouts'
    | '/'
    | '/workouts/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/add-workout'
    | '/_authenticated/workouts'
    | '/_authenticated/'
    | '/_authenticated/workouts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/add-workout': {
      id: '/_authenticated/add-workout'
      path: '/add-workout'
      fullPath: '/add-workout'
      preLoaderRoute: typeof AuthenticatedAddWorkoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workouts': {
      id: '/_authenticated/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AuthenticatedWorkoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workouts/$id': {
      id: '/_authenticated/workouts/$id'
      path: '/$id'
      fullPath: '/workouts/$id'
      preLoaderRoute: typeof AuthenticatedWorkoutsIdRouteImport
      parentRoute: typeof AuthenticatedWorkoutsRoute
    }
  }
}

interface AuthenticatedWorkoutsRouteChildren {
  AuthenticatedWorkoutsIdRoute: typeof AuthenticatedWorkoutsIdRoute
}

const AuthenticatedWorkoutsRouteChildren: AuthenticatedWorkoutsRouteChildren = {
  AuthenticatedWorkoutsIdRoute: AuthenticatedWorkoutsIdRoute,
}

const AuthenticatedWorkoutsRouteWithChildren =
  AuthenticatedWorkoutsRoute._addFileChildren(
    AuthenticatedWorkoutsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddWorkoutRoute: typeof AuthenticatedAddWorkoutRoute
  AuthenticatedWorkoutsRoute: typeof AuthenticatedWorkoutsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddWorkoutRoute: AuthenticatedAddWorkoutRoute,
  AuthenticatedWorkoutsRoute: AuthenticatedWorkoutsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
