/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddWorkoutRouteImport } from './routes/add-workout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as WorkoutsIdRouteImport } from './routes/workouts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddWorkoutRoute = AddWorkoutRouteImport.update({
  id: '/add-workout',
  path: '/add-workout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIdRoute = WorkoutsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkoutsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-workout': typeof AddWorkoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/workouts/$id': typeof WorkoutsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-workout': typeof AddWorkoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/workouts/$id': typeof WorkoutsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-workout': typeof AddWorkoutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/workouts/$id': typeof WorkoutsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-workout'
    | '/login'
    | '/register'
    | '/workouts'
    | '/workouts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-workout'
    | '/login'
    | '/register'
    | '/workouts'
    | '/workouts/$id'
  id:
    | '__root__'
    | '/'
    | '/add-workout'
    | '/login'
    | '/register'
    | '/workouts'
    | '/workouts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddWorkoutRoute: typeof AddWorkoutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  WorkoutsRoute: typeof WorkoutsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-workout': {
      id: '/add-workout'
      path: '/add-workout'
      fullPath: '/add-workout'
      preLoaderRoute: typeof AddWorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$id': {
      id: '/workouts/$id'
      path: '/$id'
      fullPath: '/workouts/$id'
      preLoaderRoute: typeof WorkoutsIdRouteImport
      parentRoute: typeof WorkoutsRoute
    }
  }
}

interface WorkoutsRouteChildren {
  WorkoutsIdRoute: typeof WorkoutsIdRoute
}

const WorkoutsRouteChildren: WorkoutsRouteChildren = {
  WorkoutsIdRoute: WorkoutsIdRoute,
}

const WorkoutsRouteWithChildren = WorkoutsRoute._addFileChildren(
  WorkoutsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddWorkoutRoute: AddWorkoutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  WorkoutsRoute: WorkoutsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
