// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phkdvheyvidzcvnmdely.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoa2R2aGV5dmlkemN2bm1kZWx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk2NTE1ODAsImV4cCI6MjEwNTIyNzU4MH0.XbxQNh6ctOc0twY0cyuf2XxsxVAVkO1G7ZFqhH-LJqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});